CREATE TABLE IF NOT EXISTS providers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS hotels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);

-- ingestion files
CREATE TABLE IF NOT EXISTS ingestion_files (
  id VARCHAR(64) PRIMARY KEY,
  file_name VARCHAR(255),
  processed_at TIMESTAMP,              -- H2: no TIMESTAMPTZ
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  error CLOB
);

-- reviews
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,            -- H2 replacement for BIGSERIAL
  provider_id INTEGER NOT NULL,
  hotel_id BIGINT NOT NULL,                                           -- match hotels.id type
  external_review_id BIGINT NOT NULL,
  rating DECIMAL(3,1),
  review_date TIMESTAMP,                                            -- H2: no TIMESTAMPTZ
  title VARCHAR(500),
  comment_text CLOB,
  positives CLOB,
  negatives CLOB,
  reviewer_country VARCHAR(64),
  language_code VARCHAR(8),
  raw_json JSON,                                                    -- H2 supports JSON (not JSONB)
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_reviews_provider
    FOREIGN KEY (provider_id) REFERENCES providers(id),
  CONSTRAINT fk_reviews_hotel
    FOREIGN KEY (hotel_id) REFERENCES hotels(id)
);

-- Idempotency: one external review per provider
CREATE UNIQUE INDEX IF NOT EXISTS ux_review_provider_external
  ON reviews(provider_id, external_review_id);