CREATE TABLE IF NOT EXISTS providers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS hotels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ingestion_files (
  id TEXT PRIMARY KEY,
  file_name TEXT,
  processed_at TIMESTAMP,
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  error TEXT
);

CREATE TABLE IF NOT EXISTS reviews (
  id BIGSERIAL PRIMARY KEY,
  provider_id INT NOT NULL REFERENCES providers(id),
  hotel_id BIGINT NOT NULL REFERENCES hotels(id),
  external_review_id BIGINT NOT NULL,
  rating DOUBLE PRECISION,
  review_date TIMESTAMPTZ,
  title TEXT,
  comment_text TEXT,
  positives TEXT,
  negatives TEXT,
  reviewer_country TEXT,
  language_code VARCHAR(8),
  raw_json JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Idempotency: one external review per provider
CREATE UNIQUE INDEX IF NOT EXISTS ux_review_provider_external
  ON reviews(provider_id, external_review_id);

-- Useful query paths
CREATE INDEX IF NOT EXISTS ix_reviews_provider ON reviews(provider_id);
CREATE INDEX IF NOT EXISTS ix_reviews_hotel ON reviews(hotel_id);
CREATE INDEX IF NOT EXISTS ix_reviews_date ON reviews(review_date);

-- Seed known providers
INSERT INTO providers(name) VALUES ('Agoda') ON CONFLICT DO NOTHING;
INSERT INTO providers(name) VALUES ('Booking') ON CONFLICT DO NOTHING;
INSERT INTO providers(name) VALUES ('Expedia') ON CONFLICT DO NOTHING;

-- Seed Known Hotels
INSERT INTO hotels(id,name) VALUES (10984,'Oscar Saigon Hotel') ON CONFLICT DO NOTHING;

