name: Build and Test on Commit

on:
  push:
    branches: [ master ]
    paths:
      - '**.md'
      - '**.java'
      - '**.xml'
      - '**.yml'
      - src/**
      - .github/**
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run unit tests
        run: mvn clean test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run integration tests with Testcontainers
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
        run: mvn verify

